if(PANDOC_EXECUTABLE)
    install(FILES "${PROJECT_BINARY_DIR}/manual.html"
        DESTINATION "${CMAKE_INSTALL_PREFIX}")
endif()

install(FILES LICENSE.txt DESTINATION "${CMAKE_INSTALL_PREFIX}")

install(TARGETS reTuner_CLAP DESTINATION "${CMAKE_INSTALL_LIBDIR}/clap")
install(DIRECTORY "${PROJECT_BINARY_DIR}/reTuner_artefacts/$<CONFIG>/LV2/"
    DESTINATION "${CMAKE_INSTALL_LIBDIR}/lv2"
    PATTERN "*.lib" EXCLUDE
    PATTERN "*.exp" EXCLUDE)
install(DIRECTORY "${PROJECT_BINARY_DIR}/reTuner_artefacts/$<CONFIG>/VST3/"
    DESTINATION "${CMAKE_INSTALL_LIBDIR}/vst3"
    PATTERN "*.lib" EXCLUDE
    PATTERN "*.exp" EXCLUDE)

install(TARGETS reTunerApp DESTINATION ${CMAKE_INSTALL_BINDIR})
