if(PANDOC_EXECUTABLE)
    install(FILES "${CMAKE_BINARY_DIR}/manual.html" DESTINATION "${CMAKE_INSTALL_DATADIR}/retuner")
endif()
install(FILES LICENSE.txt DESTINATION "${CMAKE_INSTALL_DATADIR}/retuner")

install(TARGETS reTuner_CLAP 
    DESTINATION "${CMAKE_INSTALL_LIBDIR}/clap")
install(DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/reTuner_artefacts/$<CONFIG>/LV2/"
    DESTINATION "${CMAKE_INSTALL_LIBDIR}/lv2")
install(DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/reTuner_artefacts/$<CONFIG>/VST3/"
    DESTINATION "${CMAKE_INSTALL_LIBDIR}/vst3")

install(TARGETS reTunerApp DESTINATION ${CMAKE_INSTALL_BINDIR})
